export const PROVIDER = {
  USER: 'USER_PROVIDER',
  TICKET: 'TICKET_PROVIDER',
  STATUS: 'STATUS_PROVIDER',
  TRACKING: 'TRACKING_PROVIDER',
  FEEDBACK: 'FEEDBACK_PROVIDER',
  TAGS: 'TAGS_PROVIDER',
  CATEGORY: 'CATEGORY_PROVIDER',
  TICKET_SCHEDULE: 'TICKET_SCHEDULE_PROVIDER',
};
